const regular = 400,
  medium = 500,
  semiBold = 600,
  bold = 700

export const typography = {
  h1: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "55px",
    letterSpacing: "0px",
    lineHeight: "60px",
    display: "block",
  },
  h2: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "33px",
    letterSpacing: "0.48px",
    lineHeight: "43px",
    display: "block",
  },
  h3: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "28px",
    letterSpacing: "0.64px",
    lineHeight: "34px",
    display: "block",
  },
  h4: {
    fontFamily: "Arial",
    fontWeight: semiBold,
    fontSize: "26px",
    letterSpacing: "0.32px",
    lineHeight: "31px",
    display: "block",
  },
  h5: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "23px",
    letterSpacing: "0.32px",
    lineHeight: "30px",
    display: "block",
  },
  h6: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "19px",
    letterSpacing: "1px",
    lineHeight: "32px",
    display: "block",
  },
  h7: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "14px",
    letterSpacing: "0.5px",
    lineHeight: "18px",
    display: "block",
  },
  h8: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "15px",
    textTransform: "uppercase",
    letterSpacing: "0.32px",
    lineHeight: "24px",
    display: "block",
  },
  h9: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "12px",
    letterSpacing: "0.32px",
    lineHeight: "15px",
    display: "block",
  },
  subtitle1: {
    fontFamily: "Arial",
    fontWeight: bold,
    fontSize: "22px",
    letterSpacing: "0.15px",
    lineHeight: "32px",
    display: "block",
  },
  subtitle2: {
    fontFamily: "Arial",
    fontWeight: bold,
    fontSize: "16px",
    letterSpacing: "0.1px",
    lineHeight: "24px",
    display: "block",
  },
  body1: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "15px",
    letterSpacing: "0.8px",
    lineHeight: "24px",
    display: "block",
  },
  body1caps: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "15px",
    letterSpacing: "0.8px",
    lineHeight: "24px",
    display: "block",
    textTransform: "uppercase",
  },
  body2: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "13px",
    letterSpacing: "0.32px",
    lineHeight: "20px",
    display: "block",
  },
  body3: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "10px",
    letterSpacing: "0.8px",
    lineHeight: "12px",
    display: "block",
  },
  buttonLarge: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "15px",
    letterSpacing: "20%",
    lineHeight: "19px",
    display: "block",
    textTransform: "uppercase",
  },
  buttonMedium: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "13px",
    letterSpacing: "20%",
    lineHeight: "17px",
    display: "block",
    textTransform: "uppercase",
  },
  buttonSmall: {
    fontFamily: "Arial",
    fontWeight: medium,
    fontSize: "12px",
    letterSpacing: "20%",
    lineHeight: "15px",
    display: "block",
    textTransform: "uppercase",
  },
  captionBold: {
    fontFamily: "Arial",
    fontWeight: bold,
    fontSize: "12px",
    letterSpacing: "0.4px",
    display: "block",
  },
  caption: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "12px",
    letterSpacing: "0.4px",
    display: "block",
  },
  overline: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "14px",
    letterSpacing: "3px",
    display: "block",
    textTransform: "uppercase",
  },
  avatarLetter: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "20px",
    letterSpacing: "0.14px",
    display: "block",
  },
  inputLabel: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "12px",
    letterSpacing: "0.15px",
    display: "block",
  },
  helperText: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "12px",
    letterSpacing: "0.4px",
    display: "block",
  },
  inputText: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "16px",
    letterSpacing: "0.15px",
    display: "block",
  },
  tooltip: {
    fontFamily: "Arial",
    fontWeight: regular,
    fontSize: "10px",
    letterSpacing: "0px",
    display: "block",
  },
}
